<?php  
include('widget-comment.php');
include('widget-tags.php');
include('widget-ad.php');
include('widget-hotpost.php');
include('widget-postlist.php');
include('widget-mostviews.php');
include('widget-social.php');
include('widget-links.php');
include('widget-special.php');
?>